
CREATE EXTENSION IF NOT EXISTS postgis;


CREATE TYPE user_role AS ENUM (
  'ADMIN', 'USER', 'TECHNICIAN'
);

CREATE TYPE report_state AS ENUM (
  'REPORTED', 'VALIDATED', 'REJECTED', 'ASSIGNED', 
  'IN_TRANSIT', 'IN_PROGRESS', 'RESOLVED', 'NO_PROCEDE'
);

CREATE TYPE severity_t AS ENUM (
  'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
);